### ISSUE TITLE
does not work when hitting enter

### ISSUE THREAD

**Issue by axyr** [novatio/silverstripe-statefulgridfield#2]
steps to reproduce:

In Files : 
1. open gridfield header
2. type in search term
3. hit enter

the filtered results show up briefly, but immediately it shows the previous result again.

**Comment by gavro** [comment]
Hm, can't reproduce in Chrome nor Firefox. Which SS version?

**Comment by axyr** [comment]
3.2

**Comment by gavro** [comment]
This was caused by "resetting" the pagination. Refactored a bit, should be fixed now.
